export const fixtures = [
  {
    id: 1,
    home_name: "Tottenham",
    away_name: "Man City",
    competitionId: 1,
    competition: "Premier League",
    time: "12:30",
    date: "10-1-2024",
    favorite: false,
  },
  {
    id: 2,
    home_name: "Liverpool",
    away_name: "Manchester United",
    competitionId: 1,
    competition: "Premier League",
    time: "15:00",
    date: "10-1-2024",
    favorite: true,
  },
  {
    id: 3,
    home_name: "Valencia",
    away_name: "Real Madrid",
    competitionId: 2,
    competition: "LaLiga Santander",
    time: "18:30",
    date: "10-1-2024",
    favorite: false,
  },
  {
    id: 4,
    home_name: "Lyon",
    away_name: "Nice",
    competitionId: 3,
    competition: "Ligue 1",
    time: "10:30",
    date: "11-1-2024",
    favorite: true,
  },
  {
    id: 5,
    home_name: "Inter Milan",
    away_name: "AC Milan",
    competitionId: 4,
    competition: "Serie A",
    time: "13:30",
    date: "11-1-2024",
    favorite: false,
  },
  {
    id: 6,
    home_name: "Ajax",
    away_name: "Az",
    competitionId: 5,
    competition: "Eredivisie",
    time: "12:00",
    date: "11-1-2024",
    favorite: true,
  },
  // ... Additional fixtures for 11-1-2024

  // Additional fixtures for 12-1-2024
  {
    id: 10,
    home_name: "Chelsea",
    away_name: "Arsenal",
    competitionId: 1,
    competition: "Premier League",
    time: "15:30",
    date: "12-1-2024",
    favorite: false,
  },
  {
    id: 11,
    home_name: "Barcelona",
    away_name: "Atletico Madrid",
    competitionId: 2,
    competition: "LaLiga Santander",
    time: "20:00",
    date: "12-1-2024",
    favorite: true,
  },
  {
    id: 12,
    home_name: "Paris Saint-Germain",
    away_name: "Marseille",
    competitionId: 3,
    competition: "Ligue 1",
    time: "11:00",
    date: "12-1-2024",
    favorite: false,
  },
  {
    id: 13,
    home_name: "Juventus",
    away_name: "Roma",
    competitionId: 4,
    competition: "Serie A",
    time: "14:30",
    date: "12-1-2024",
    favorite: true,
  },
  {
    id: 14,
    home_name: "Feyenoord",
    away_name: "PSV",
    competitionId: 5,
    competition: "Eredivisie",
    time: "13:15",
    date: "12-1-2024",
    favorite: false,
  },
  // ... Additional fixtures for 12-1-2024

  // Additional fixtures for 13-1-2024
  {
    id: 18,
    home_name: "Manchester City",
    away_name: "Chelsea",
    competitionId: 1,
    competition: "Premier League",
    time: "16:30",
    date: "13-1-2024",
    favorite: true,
  },
  {
    id: 19,
    home_name: "Real Madrid",
    away_name: "Barcelona",
    competitionId: 2,
    competition: "LaLiga Santander",
    time: "19:45",
    date: "13-1-2024",
    favorite: false,
  },
  {
    id: 20,
    home_name: "Nice",
    away_name: "Paris Saint-Germain",
    competitionId: 3,
    competition: "Ligue 1",
    time: "12:30",
    date: "13-1-2024",
    favorite: true,
  },
  {
    id: 21,
    home_name: "AC Milan",
    away_name: "Juventus",
    competitionId: 4,
    competition: "Serie A",
    time: "15:00",
    date: "13-1-2024",
    favorite: false,
  },
  {
    id: 22,
    home_name: "Az",
    away_name: "Feyenoord",
    competitionId: 5,
    competition: "Eredivisie",
    time: "14:45",
    date: "13-1-2024",
    favorite: true,
  },
  // ... Additional fixtures for 13-1-2024

  // Additional fixtures for 14-1-2024
  {
    id: 26,
    home_name: "Manchester United",
    away_name: "Arsenal",
    competitionId: 1,
    competition: "Premier League",
    time: "14:00",
    date: "14-1-2024",
    favorite: false,
  },
  {
    id: 27,
    home_name: "Atletico Madrid",
    away_name: "Real Madrid",
    competitionId: 2,
    competition: "LaLiga Santander",
    time: "17:30",
    date: "14-1-2024",
    favorite: true,
  },
  {
    id: 28,
    home_name: "Marseille",
    away_name: "Lyon",
    competitionId: 3,
    competition: "Ligue 1",
    time: "11:15",
    date: "14-1-2024",
    favorite: false,
  },
  {
    id: 29,
    home_name: "Roma",
    away_name: "Inter Milan",
    competitionId: 4,
    competition: "Serie A",
    time: "13:45",
    date: "14-1-2024",
    favorite: true,
  },
  {
    id: 30,
    home_name: "Sparta",
    away_name: "Ajax",
    competitionId: 5,
    competition: "Eredivisie",
    time: "13:30",
    date: "14-1-2024",
    favorite: false,
  },
  {
    id: 31,
    home_name: "Tottenham",
    away_name: "Liverpool",
    competitionId: 1,
    competition: "Premier League",
    time: "15:30",
    date: "14-1-2024",
    favorite: true,
  },
  {
    id: 32,
    home_name: "Manchester United",
    away_name: "Manchester City",
    competitionId: 1,
    competition: "Premier League",
    time: "18:00",
    date: "14-1-2024",
    favorite: false,
  },
  {
    id: 33,
    home_name: "Real Madrid",
    away_name: "Barcelona",
    competitionId: 2,
    competition: "LaLiga Santander",
    time: "20:30",
    date: "14-1-2024",
    favorite: true,
  },
  {
    id: 34,
    home_name: "Valencia",
    away_name: "Atletico Madrid",
    competitionId: 2,
    competition: "LaLiga Santander",
    time: "14:00",
    date: "14-1-2024",
    favorite: false,
  },
  {
    id: 35,
    home_name: "Lyon",
    away_name: "Paris Saint-Germain",
    competitionId: 3,
    competition: "Ligue 1",
    time: "16:30",
    date: "14-1-2024",
    favorite: true,
  },
  {
    id: 36,
    home_name: "Marseille",
    away_name: "Nice",
    competitionId: 3,
    competition: "Ligue 1",
    time: "19:00",
    date: "14-1-2024",
    favorite: false,
  },
  {
    id: 37,
    home_name: "AC Milan",
    away_name: "Juventus",
    competitionId: 4,
    competition: "Serie A",
    time: "12:45",
    date: "14-1-2024",
    favorite: true,
  },
  {
    id: 38,
    home_name: "Inter Milan",
    away_name: "Roma",
    competitionId: 4,
    competition: "Serie A",
    time: "15:15",
    date: "14-1-2024",
    favorite: false,
  },
  {
    id: 39,
    home_name: "Ajax",
    away_name: "Feyenoord",
    competitionId: 5,
    competition: "Eredivisie",
    time: "14:30",
    date: "14-1-2024",
    favorite: true,
  },
  {
    id: 40,
    home_name: "PSV",
    away_name: "Az",
    competitionId: 5,
    competition: "Eredivisie",
    time: "17:00",
    date: "14-1-2024",
    favorite: false,
  },
  {
    id: 50,
    home_name: "Heracles",
    away_name: "Almere City",
    competitionId: 5,
    competition: "Eredivisie",
    time: "17:45",
    date: "9-1-2024",
    favorite: false,
  },
];
